@host=http://localhost:5247

@adminId=d45a57f6-2c1d-42da-85b0-0fc1968cc950

Post {{host}}/Subscriptions/
Content-Type: application/json

{
    "SubscriptionType": "Free",
    "AdminId": "{{adminId}}"
}
